### ISSUE TITLE
Sakuli error throws exception while forwarding

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli-enterprise-forwarder#88]
V 2.4.0
```
  ____            _              _   _ 
 / ___|    __ _  | | __  _   _  | | (_)
 \___ \   / _` | | |/ / | | | | | | | |
  ___) | | (_| | |   <  | |_| | | | | |
 |____/   \__,_| |_|\_\  \__,_| |_| |_|
                                       
========================================
Initialized Sakuli with 1 Testcases
Writing logs to: _logs/sakuli.log
Started execution
→ Started Testsuite CM Sakuli Demo
  → Started Testcase Pink Coffee
   ✓ Finished Step CM Track login with state Ok...............................................................................................................................5.865s
   ✓ Finished Step Create CM Track Ticket with state Ok......................................................................................................................23.231s
   ✓ Finished Step Indexing with state Ok.....................................................................................................................................3.003s
   ✓ Finished Step CM client login with state Ok..............................................................................................................................6.128s
   ✓ Finished Step Search ticket with state Ok................................................................................................................................2.714s
   ✓ Finished Step Validate ticket with state Ok..............................................................................................................................4.921s
   ✓ Finished Step Close Ticket in CM-Client with state Ok...................................................................................................................10.419s
   ✓ Finished Step Connect to Windows VM with state Ok.......................................................................................................................20.128s
   ✓ Finished Step Maintain CM Ticket Number in Excel with state Ok..........................................................................................................14.449s
   ✓ Finished Step Draw Sakuli Logo in Paint with state Ok....................................................................................................................6.549s
   ✓ Finished Step Sign out from VM with state Ok.............................................................................................................................1.906s
   ✓ Finished Step Close remmina with state Ok................................................................................................................................0.001s
   ⚠ Finished Step UNNAMED with state Error..................................................................................................................................31.353s
  ⚠ Finished Testcase Pink Coffee with state Error..........................................................................................................................130.719s
⚠ Finished Testsuite CM Sakuli Demo with state Error........................................................................................................................130.815s
End execution
Error during Execution: 
TypeError: Cannot read property 'length' of undefined
at /headless/.nvm/versions/node/v12.18.4/lib/node_modules/@sakuli/forwarder-gearman/node_modules/@sakuli/result-builder-commons/dist/templates/render/render-error.function.js:1:4309
    at Array.map (<anonymous>)
    at Object.exports.<computed> [as renderCaseErrors] (/headless/.nvm/versions/node/v12.18.4/lib/node_modules/@sakuli/forwarder-gearman/node_modules/@sakuli/result-builder-commons/dist/templates/render/render-error.function.js:1:4143)
    at /headless/.nvm/versions/node/v12.18.4/lib/node_modules/@sakuli/forwarder-gearman/node_modules/@sakuli/result-builder-commons/dist/templates/render/render-error.function.js:1:3505
    at Array.map (<anonymous>)
    at Object.exports.<computed> [as renderSuiteErrors] (/headless/.nvm/versions/node/v12.18.4/lib/node_modules/@sakuli/forwarder-gearman/node_modules/@sakuli/result-builder-commons/dist/templates/render/render-error.function.js:1:3449)
    at renderError (/headless/.nvm/versions/node/v12.18.4/lib/node_modules/@sakuli/forwarder-gearman/node_modules/@sakuli/result-builder-commons/dist/templates/short-summary/short-summary-suite.function.js:1:4173)
    at Object.exports.<computed> [as renderShortSuiteSummary] (/headless/.nvm/versions/node/v12.18.4/lib/node_modules/@sakuli/forwarder-gearman/node_modules/@sakuli/result-builder-commons/dist/templates/short-summary/short-summary-suite.function.js:1:3790)
    at Object.exports.<computed> [as renderShortSummary] (/headless/.nvm/versions/node/v12.18.4/lib/node_modules/@sakuli/forwarder-gearman/node_modules/@sakuli/result-builder-commons/dist/templates/short-summary/index.js:1:3240)
    at OmdTestResultOutputBuilder.render (/headless/.nvm/versions/node/v12.18.4/lib/node_modules/@sakuli/forwarder-gearman/node_modules/@sakuli/result-builder-omd/dist/index.js:1:3856)
Action timed out after 25000
Action timed out after 25000
Failed to perform step :
Failed to perform action wait:
```

Seems to relate to
https://github.com/sakuli/sakuli-enterprise-forwarder/blob/348604f6e6b3ba3c00aff2f229fce8c9a91d5b0b/packages/sakuli-result-builder-commons/src/templates/render/render-error.function.ts#L36-L37

or 

https://github.com/sakuli/sakuli-enterprise-forwarder/blob/348604f6e6b3ba3c00aff2f229fce8c9a91d5b0b/packages/sakuli-result-builder-commons/src/templates/render/render-error.function.ts#L19-L20

**Comment by cliffle** [comment]
#### Forwarder
Here is the stack of the error
```
"Cannot read property 'length' of undefined"
TypeError: Cannot read property 'length' of undefined
    at /home/cliff/gitprojects/sakuli-enterprise-forwarder/packages/sakuli-result-builder-commons/dist/templates/render/render-error.function.js:39:34
    at Array.map (<anonymous>)
    at Object.renderCaseErrors (/home/cliff/gitprojects/sakuli-enterprise-forwarder/packages/sakuli-result-builder-commons/dist/templates/render/render-error.function.js:36:10)
    at /home/cliff/gitprojects/sakuli-enterprise-forwarder/packages/sakuli-result-builder-commons/dist/templates/render/render-error.function.js:20:35
    at Array.map (<anonymous>)
    at Object.renderSuiteErrors (/home/cliff/gitprojects/sakuli-enterprise-forwarder/packages/sakuli-result-builder-commons/dist/templates/render/render-error.function.js:19:10)
    at renderError (/home/cliff/gitprojects/sakuli-enterprise-forwarder/packages/sakuli-result-builder-commons/dist/templates/short-summary/short-summary-suite.function.js:21:40)
    at Object.renderShortSuiteSummary (/home/cliff/gitprojects/sakuli-enterprise-forwarder/packages/sakuli-result-builder-commons/dist/templates/short-summary/short-summary-suite.function.js:13:80)
    at Object.renderShortSummary (/home/cliff/gitprojects/sakuli-enterprise-forwarder/packages/sakuli-result-builder-commons/dist/templates/short-summary/index.js:17:51)
    at CheckMkTestResultOutputBuilder.render (/home/cliff/gitprojects/sakuli-enterprise-forwarder/packages/sakuli-forwarder-check_mk/node_modules/@sakuli/result-builder-checkmk/dist/index.js:6:54)
```
As you suspected, the error is thrown here:
https://github.com/sakuli/sakuli-enterprise-forwarder/blob/348604f6e6b3ba3c00aff2f229fce8c9a91d5b0b/packages/sakuli-result-builder-commons/src/templates/render/render-error.function.ts#L37

`stepError` is assigned through `renderError()`, which is:
https://github.com/sakuli/sakuli-enterprise-forwarder/blob/348604f6e6b3ba3c00aff2f229fce8c9a91d5b0b/packages/sakuli-result-builder-commons/src/templates/render/render-error.function.ts#L6

#### Sakuli Core
So to reproduce this error we can use this testcase:
```typescript
(async () => {
  const testCase = new TestCase("Fry an egg");
  try {
    await _wait(1000, () => _isVisible(_div("does not exist")));
    testCase.startStep("Create error");
  } catch (e) {
    await testCase.handleException(e);
  } finally {
    testCase.saveResult();
  }
})();
```

This will cause the action to be rejected with the **string** `Action timed out after ${maxDuration} ms` through the timeout function in [poll-action.function.ts](https://github.com/sakuli/sakuli/blob/00ea93d8cb0db4185262102b8657b4bd7ba5aa82/packages/sakuli-legacy/src/context/sahi/action/poll-action.function.ts#L41).

When we look back to the implementation of `renderError` in the forwarder, we can see that if `error="Action timed out after 1000 ms"` that `testDataEntity.error` would be the string, whereas `error.message` is `undefined`.

#### Root Cause
When `handleException(e)` is called, we don't have a check that ensures that e is an `Error`.
https://github.com/sakuli/sakuli/blob/00ea93d8cb0db4185262102b8657b4bd7ba5aa82/packages/sakuli-legacy/src/context/common/test-case/test-case.class.ts#L144
This means we can reject/throw anything during the test execution and this will result in an error. 
My proposal is to add a type guard for `e` before the test step is updated.



Notes:
- We can revert the changes in https://github.com/sakuli/sakuli/commit/e8a22c36aee11b1e1ad7d16fa7bdc83fb9eb5c8f because `Error` always has a `message`(See [Typescript Error interface](https://github.com/microsoft/TypeScript/blob/66ecfcbd04b8234855a673adb85e5cff3f8458d4/lib/lib.es5.d.ts#L972))
- To output the error stack for an error in a forwarder, we need to add `e.stack` as data for the logger [here](https://github.com/sakuli/sakuli/blob/e8a22c36aee11b1e1ad7d16fa7bdc83fb9eb5c8f/packages/sakuli-core/src/forwarder/connect-forwarder-to-test-execution-context.function.ts#L62)
- https://github.com/sakuli/sakuli/blob/00ea93d8cb0db4185262102b8657b4bd7ba5aa82/packages/sakuli-legacy/src/context/common/application/sakuli-application.class.ts#L43 and https://github.com/sakuli/sakuli/blob/00ea93d8cb0db4185262102b8657b4bd7ba5aa82/packages/sakuli-legacy/src/context/common/environment/sakuli-environment.class.ts#L303 probably also needs to be changed to reject an Error

**Comment by svettwer** [comment]
Renamed issue as it could occur on every forwarder depending on the forwarder commons, because the root cause is located in commons.

**Comment by svettwer** [comment]
Extracted some changes to dedicated issue.

**Comment by svettwer** [comment]
All issues have been extracted into sakuli/sakuli#600 and sakuli/sakuli#601. As there is nothing left to change in the forwarders, this issue will be closed in favor of the both mentioned issues.
